### ISSUE TITLE
Remove joda-time dependency

### ISSUE THREAD

**Issue by danhawkes** [redbooth/react-native-auto-updater#15]
Joda-time is a huge JAR, and including it adds [557 KB](http://search.maven.org/#artifactdetails|joda-time|joda-time|2.1|jar) to the APK size, as well as slowing startup time. 

I think it's only used to calculate the number days since last updated, which could easily be done with the built-in Calendar class. Will submit a PR to do so if interested.

**Comment by rahuljiresal** [comment]
Thanks @danhawkes! Yes absolutely, a PR for that would be very welcome.
