### ISSUE TITLE
[improvement] extend ReactNativeAutoUpdaterActivity issue

### ISSUE THREAD

**Issue by devonEdison** [redbooth/react-native-auto-updater#23]
If it's ok , hope you can make this **react-native-auto-updater** more like **modularized code**, which can let Mainactivity not only can extend ReactNativeAutoUpdaterActivity, but also extend Activity.

As far as I know, android RN can let the Mainactivity extend activity and create ReactInstance
like this:

```
        mReactInstanceManager = ReactInstanceManager.builder() 
                .setApplication(getApplication())
                .setBundleAssetName(MainActivity.bundlAssetsName)
                .setJSMainModuleName(MainActivity.jsModleName)
                .addPackage(new MainReactPackage())
                .addPackage(new ReactVideoPackage())
                .addPackage(new CommandpReactPackage(MainActivity.this, progressLayout))
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
```

to use RN, if not using the ReactActivity.
So hopefully you can let this source code(**react-native-auto-updater**), more better to make it like a library(module) in Android.

@rahuljiresal

**Comment by rahuljiresal** [comment]
@devonEdison Currently, if you want to extend `Activity` with React Native, you have to check the source of `ReactActivity` and find out what it does, then replicate it in your subclass of `Activity`.

The same way, if you check what [`ReactNativeAutoUpdaterActivity`](https://github.com/aerofs/react-native-auto-updater/blob/master/android/src/main/java/com/aerofs/reactnativeautoupdater/ReactNativeAutoUpdaterActivity.java) does, you can very easily replicate that functionality in your subclass of activity. Here are the general steps.
1. Get an instance of `ReactNativeAutoUpdater`.
2. Set the necessary properties.
3. Check for updates.
4. (Optional) Implement methods in `ReactNativeAutoUpdater.Interface`.

Hope that helps.

**Comment by devonEdison** [comment]
```
    public static ReactNativeAutoUpdater mReactUpdateInstanceManager;
        //check renew activity
        if(mReactUpdateInstanceManager == null){
            mReactUpdateInstanceManager = ReactNativeAutoUpdater.getInstance(this.getApplicationContext());
            mReactUpdateInstanceManager.setUpdateMetadataUrl("http://192.168.66.220:8888/update.android.json")
                    .setMetadataAssetName("metadata.android.json")
                 .setUpdateFrequency(ReactNativeAutoUpdater.ReactNativeAutoUpdaterFrequency.EACH_TIME)
                    .setUpdateTypesToDownload(ReactNativeAutoUpdater.ReactNativeAutoUpdaterUpdateType.PATCH)
                    .setHostnameForRelativeDownloadURLs( "http://192.168.66.220:8888")
                    .showProgress(true)
                    .setParentActivity(MainActivity.this)
                    .checkForUpdates();
        }
        if(mReactInstanceManager == null) {
            mReactInstanceManager = ReactInstanceManager.builder()
                    .setApplication(getApplication())
                    .setBundleAssetName(MainActivity.bundlAssetsName)
                    .setJSMainModuleName(MainActivity.jsModleName)
                    .addPackage(new ReactNativeAutoUpdaterPackage())
                    .addPackage(new MainReactPackage())
                    .addPackage(new ReactVideoPackage())
                    .addPackage(new CommandpReactPackage(MainActivity.this, progressLayout))
                    .setUseDeveloperSupport(BuildConfig.DEBUG)
                    .setInitialLifecycleState(LifecycleState.RESUMED)
                    .build();
        }
```

@rahuljiresal 
thanks for your help,and it works on my MainActivity extend Activitiy
sharing my work~

**Comment by devonEdison** [comment]
this issue can be closed.
