### ISSUE TITLE
App crashes when data-connection is off

### ISSUE THREAD

**Issue by rameshvishnoi90904** [redbooth/react-native-auto-updater#25]

**Comment by rahuljiresal** [comment]
Is this Android or iOS?

**Comment by rameshvishnoi90904** [comment]
@rahuljiresal i am working on Android.

**Comment by happyming9527** [comment]
me too. when net is not connected,on android,the app will crash.can anybody help?

**Comment by rahuljiresal** [comment]
Thanks for the update guys. I'm really busy the next couple of weeks, I'll try to get to it on the weekend, but if you have a Pull Request, I'll be more than happy to take a look at it.

**Comment by shraddha1704** [comment]
I am working on an Android app and facing the same issue.

**Comment by FuYaoDe** [comment]
@rahuljiresal,  I fix it at pr #33   check it out ~

**Comment by sangdesigner** [comment]
i am also facing same issue app crashing checking updates then app crash
