### ISSUE TITLE
Where should metadata.json go?

### ISSUE THREAD

**Issue by naji247** [redbooth/react-native-auto-updater#27]
Hey guys, I'm pretty sure my app isn't able to find my metadata.json ):

Where should it go for the default location? I put it in my ios/ folder but alas it isn't looking there. Am I supposed to make xCode recognize it some way? When I try to print my metadata.json NSURL location I get nothing, when I print my defaulJSCode location I get:

file:///Users/naseem.alnaji/Library/Developer/CoreSimulator/Devices/29F61826-651D-4552-8C94-E784629661A8/data/Containers/Bundle/Application/B8FBC428-781F-4A51-8BEA-B073AEDE5A4F/DogShow.app/main.jsbundle

Is it supposed to be in that folder somehow through the build process..?

**Comment by rahuljiresal** [comment]
It should go in your main project (just dragging and dropping should do it).

Additionally, to make sure it is being included in the app, check project's Build Phases > Copy Bundle Resources. It should be included in there.

**Comment by naji247** [comment]
Thank you rahul! I think the second piece of advice was what I was missing! :)
