### ISSUE TITLE
just a question about old apk

### ISSUE THREAD

**Issue by leonardgithub** [redbooth/react-native-auto-updater#28]
HI, on android, I generated two apk for the same project, just some UI differences between these two apk. Then I install apk A in the simulator first, open apk A and updated to apk B on the server side successfully, but when I uninstall apk B, and install A, the UI is of B, not of A. Why? Is there cache in the simulator? Or the apk in the folder will be overwritten when using react-native-auto-updater? Thanks

**Comment by leonardgithub** [comment]
Another question: when the new version is detected and the dialog for update is shown, the app will be updated to new version without clicking button Later or Now. Why? is it forced update?

**Comment by rahuljiresal** [comment]
Okay, so I'm assuming you're using React Native, and these UI differences in the APKs are due to the changes in the Javascript code (and not the native Java code). In this scenario, the changes you see will not be because of the APK change, but because of the JS code change. When you install apk A (which contains JS version 'a'), and then update to JS version 'b', you will only see the UI defined by the JS version 'b' no matter what APK you're using (a or b).

Another thing, I don't understand why you need to create multiple APKs. If you're not making changes to any native modules, Java code, or manifest files (etc), then you won't have to create new APK files. Just upgrading your JS code should do it. Thats the beauty of React Native.

Hope this helps.

**Comment by rahuljiresal** [comment]
About your second question, the updater is written with the developers in mind, and not the end users. In most cases, when there is a new update, developers want to enforce it on the users, to make sure everybody is on the newest version, using newest features, and keeping them secure. Also getting newest user behavior data is only possible when users are up to date, and as developers, we need that.

The dialog shown to the user says "An update has been downloaded. Do you want to apply it now?". And that is just to make sure the user is not doing something important right now (e.g. filling out a long form, etc). The update has already been downloaded and it will be applied the next time app starts anyway. If the user wants it or not.

**Comment by leonardgithub** [comment]
Thanks for you reply.
Yes, my condition is as you assumed, and no differences in Java code.
The reason I generated two APKs is I plan to generate the two different js bundles, and test the auto-updater plugin.
Is "Just upgrading your JS code should do it. Thats the beauty of React Native" for dev environment or for production environment? If for dev I know there is live load provided by react native, if for prodution, do you mean "just generate the new js bundle and use react-native-auto-updater for update"? 
For the 2nd question, I think I misunderstanding the dialog text, it is Later, I consider it as "Not Update", so you are right.

**Comment by leonardgithub** [comment]
@rahuljiresal 
Thanks for you reply.
Yes, my condition is as you assumed, and no differences in Java code.

The reason I generated two APKs is I plan to generate the two different js bundles, and test the auto-updater plugin.

Is "Just upgrading your JS code should do it. Thats the beauty of React Native" for dev environment or for production environment? If for dev I know there is live load provided by react native, if for prodution, do you mean "just generate the new js bundle and use react-native-auto-updater for update"? 

For the 2nd question, I think I misunderstanding the dialog text, it is Later, I consider it as "Not Update", so you are right.

**Comment by rahuljiresal** [comment]
You don't need two APKs to generate two different JS bundles. You can generate different JS bundles by using the `react-native bundle` command.

**Comment by leonardgithub** [comment]
@rahuljiresal Get it, thanks!
