### ISSUE TITLE
Update not good enough

### ISSUE THREAD

**Issue by WhatAKitty** [redbooth/react-native-auto-updater#29]
It not ok if you checked 'no' option but has been updated already next time you open.
I think it will be good that dropping tmp jsbundle if someone checked 'no' .
And If I checked 'yes', The image that have been in assets folder will not show after updating.

**Comment by rahuljiresal** [comment]
It is not a user's decision to apply the updates. It is the developer's decision. The user just chooses if it will be applied right now, or later (so it doesn't interrupt what he's currently doing).

If the developer wants to give user a choice to download an update or not, he can have that setting in his app, and based on the value of the setting, he can write code that decides whether to download the update or not.

About the assets, `react-native-auto-updater` doesn't support assets yet. I'll be working on that soon. I would also appreciate a PR if you would.
