### ISSUE TITLE
[improvement] Add required imports to Android Usage section in Readme

### ISSUE THREAD

**Issue by c-h-** [redbooth/react-native-auto-updater#30]
I had to go into the Example app folder to figure out which Android imports were required in the MainActivity in order for the app to compile.

Perhaps more experienced developers know somehow which imports are required, but it would be nice if they were in the setup documentation in Readme :)

Imports I had to include in MainActivity.java:

``` java
import com.aerofs.reactnativeautoupdater.ReactNativeAutoUpdater;
import com.aerofs.reactnativeautoupdater.ReactNativeAutoUpdater.ReactNativeAutoUpdaterUpdateType;
import com.aerofs.reactnativeautoupdater.ReactNativeAutoUpdater.ReactNativeAutoUpdaterFrequency;
import com.aerofs.reactnativeautoupdater.ReactNativeAutoUpdaterActivity;
import com.aerofs.reactnativeautoupdater.ReactNativeAutoUpdaterPackage;

import javax.annotation.Nullable;
```

**Comment by rahuljiresal** [comment]
Thanks! I didn't think it was needed because if you're using a decent IDE, it does that for you.
Anyways, I added that to the README.
