### ISSUE TITLE
Confusion for newbie

### ISSUE THREAD

**Issue by steezeburger** [redbooth/react-native-auto-updater#36]
Hey all, this is my first day with react-native-auto-uploader, and coincidentally my first day with mobile dev and with react-native. I'm a little confused on where in appDelegate.m we actually specify where the new build is downloaded from.

I got the updating working, but I get an error immediately that there's an unexpected ':' in main.jsbundle line 2.
Is this main.jsbundle only on the device? I'm not sure how to inspect it and fix the error, and I have a feeling it's because I'm not properly downloading the new bundle when it sees there is a new version. Now, I can't get the app working at all because it initializes with this new, incorrect main.jsbundle (at least, I think this is what is happening).

Any ideas?

**Comment by rahuljiresal** [comment]
You can put breakpoints in your obj-C code to verify the value of `latestJSCodeLocation`. That will tell you if your JS is what you downloaded or what you shipped with the app. In any case, looks like your JS (either the shipped one or downloaded one) has that unexpected token problem.

Most likely, the JS you downloaded has the problem. And also, most likely, it is not a problem with the download process. Only if the download (and save) is successful, the new JS is loaded. Otherwise, it doesn't even bother.

Hope this helps.

**Comment by steezeburger** [comment]
Thanks for the quick reply!

Does this mean I need to explicitly define my latestJSCodeLocation? I see the assignment in AppDelegate.m, but when I add the breakpoints as you suggested, it seems that both latestJSCodeLocation and defaultJSCodeLocation are nil.

I just copy/pasted from the example so

`NSURL* defaultJSCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];`

and 

`NSURL* latestJSCodeLocation = [updater latestJSCodeLocation];`
respectively

Edit: I'm actually getting some hex for latestJSCodeLocation

**Comment by rahuljiresal** [comment]
Yes, you need to tell where the `defaultJSCodeLocation` is. This is for use before RNAU fetches the updated version. Once the updated version is fetched, then it will stop using the default JS code and use the downloaded one instead.

**Comment by steezeburger** [comment]
I do get a defaultJSCodeLocation, I was using the breakpoints wrong. It's set in the code above. I'm just confused about the latestJSCodeLocation. 

It's a hex value, but where does the app actually try to download the new bundle from? It checks the metadata.json file, but I'm lost as to where it's actually finding the new bundle.

Edit: should I have something like `NSURL* latestJSCodeLocation = [ some url from string here ];` ? and serve my main.jsbundle from my server?

**Comment by rahuljiresal** [comment]
You provide the location in metadata.json file. You upload the metadata file somewhere and give its location to the code as shown in the example. It then look for the update in that location.

**Comment by steezeburger** [comment]
Ah, I'm sorry. I was setting that path to my metadata file. I have a much better understanding of how this is bootstrapped now though. I'm still having some other issues, but I think I can figure it out from here. 

Thanks for your time man.
