### ISSUE TITLE
When new version updated, Image will not show

### ISSUE THREAD

**Issue by yangqiong** [redbooth/react-native-auto-updater#39]
<Image source={require('../images/*.png')} /> will not show, when new version updated.

**Comment by rahuljiresal** [comment]
We don't have support for images yet. I currently don't have time to work on it, but I will do it in the next 2 weeks or so. I am open to discussions or reviewing Pull Requests if someone else is willing to write it.

**Comment by rahuljiresal** [comment]
Duplicate of #32 . Closing.
