### ISSUE TITLE
Old bundle, new js code version (Android)

### ISSUE THREAD

**Issue by DanDance** [redbooth/react-native-auto-updater#49]
I build bundle using `react-native bundle --entry-file index.android.js --platform android --dev false --bundle-output android/app/src/main/assets/index.android.bundle` bundle. Then I update this bundle and meta data json on my sever. Release apk pulls update from the server, but I cant see changes except code version. Also there is index.android.bundle.meta generated by `react-native bundle` command. May it cause this problem?

react-native@0.33.0, release apk

**Comment by ufo22940268** [comment]
Have you solved this problem?

**Comment by sangdesigner** [comment]
how to solved this?
