### ISSUE TITLE
Can we expect this working in Android?

### ISSUE THREAD

**Issue by nbastoWM** [redbooth/react-native-auto-updater#5]
This concept is amazing!
Will this be available for Android in short term?
Or can we have an hybrid app for Android and iOS and at least the iphone can dynamically update it?

**Comment by rahuljiresal** [comment]
Thanks! We will be rolling out an Android version soon. In the meanwhile, as you said, you can update iOS apps dynamically.

**Comment by rahuljiresal** [comment]
Hey @nbastoWM , ReactNativeAutoUpdater now works on Android too. Check out the repo and the ReadMe file for more info.
