### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by lwansbrough** [redbooth/react-native-auto-updater#7]
I had to read the readme to discover that this isn't hosted on npm. Can you please add this to npm under the name `react-native-auto-updater`? Also, you should move the iOS specific code into `./ios` to make it easier for potential contributors to contribute Android code in the future.

**Comment by rahuljiresal** [comment]
@lwansbrough This is not hosted on npm because there's no Javascript code involved. It doesn't need to send/receive data from the JS counterpart. The Obj-C code takes care of everything that is needed to be done. Hence it is available as a CocoaPod, which is a standard dependency manager on iOS. In future, I imagined the Android code will be available as a Gradle dependency in a separate repo.

Let me think about what needs to be done to make this available on npm.

**Comment by lwansbrough** [comment]
That's a fair case for not being on npm, agreed. All the scheduling is done through methods which are automatically exposed by React then I assume? If they aren't exposed to JS that would be a good improvement and may be an excuse to throw this on npm too :D

**Comment by rahuljiresal** [comment]
In fact, it doesn't depend on React at all! It will just download a file -- when needed to update -- from whatever location you configure it with. Then you can get the location of the downloaded/cached file and give it to React so it loads the JS code from there. ReactNativeAutoUpdater doesn't even check if the file it is downloading is valid JS code. It never uses anything exposed by React, just uses native iOS/Cocoa stuff.

**Comment by lwansbrough** [comment]
Interesting, thanks for the insight!

**Comment by rahuljiresal** [comment]
@lwansbrough here, now this is available as an NPM package -- https://www.npmjs.com/package/react-native-auto-updater. Will shortly remove the CocoaPod and update the ReadMe files.

**Comment by lwansbrough** [comment]
Cool! Nice work, thank you.

**Comment by lwansbrough** [comment]
FYI there's also rnpm (React Native Package Manager) which basically handles the installation of packages. It's good that you have the full instructions there but just for your own reference you can use rnpm link as well. Cheers!

**Comment by rahuljiresal** [comment]
Oh, thanks for that pointer. It looks pretty cool. I think the user will still have to add the Header Search Path manually though. It is unusual for React Native packages to have to write Obj-C code too.

**Comment by lwansbrough** [comment]
That stuff is managed in the XCode project so it should be managed as far as I know. I haven't checked though. I have installed native modules with it and haven't had to modify header search paths though.
