### ISSUE TITLE
`fatal repo not found` when installing through cocoapod

### ISSUE THREAD

**Issue by abelsoares** [redbooth/react-native-auto-updater#8]
The repo url is not updated in `ReactNativeAutoUpdater.podspec`, causing a `fatal repo not found` when installing the pod.

**Comment by rahuljiresal** [comment]
@abelsoares Thanks for bringing this to my notice. We changed the name of the repo to maintain consistency in all our repos, hence the error. It has been fixed now, give it a try again and let me know if it doesn't work for you.
